language: node_js
node_js:
- node
script:
- 
deploy:
  provider: firebase
  token:
    secure: "V1iUKV38mvL3QCr6ZVHkyCouwQYClOc+uMmU6jN/6uhmCiRDmAmsTISd3VwW5fhwlOqS2Ho9nzP78VVctNeH3wZ0jAKr6E6U6qXbWvc7WQ4apWPspFfO90zYwXIcBXByuhQAvGA3e81bj+sBOZPovVo9zqPeBhGDtGQj+RcPqj45LiXcxgWpEGj2mNmjAeo2+g7MdtYxhvnFF0Of81x8jizVeik8tiiEutXI30z7GjzGZDp+3RIHLcDeg9N0FvIiqFFQy/JVxar/Vs5aHV1JJOs+RSOq9fhvN8+M/44JFFAG8ypVB6uxebr9/jDkeqJ9ztwioZvm8XDjUUcrvQXNQqYw/QOSq9U6f7dik7PUHNjoh97IW5iYH03Kjc0Np8Ls/pcZPLT9endjLWlBVRKKX2S7XxMKR/TCZ7wlzFCHRHcIAM7o568gzNcDXwylyRTVXRdywyRTUAY7z/ri5WRHR5FxEXAGyzh+6jga33GFi19wexn4S2XSfxWAvHz2dukVSK/AMLd0ZVIwA5LEhrRZO5+lzYObBEk0ylgB4zuWR8y5D+niZJbiyUSFiBrda30n5+sdZIlrbHrbzCk2flFJLLACzU5lItFKEtFU+pyCr3zFwS5JmAwE6R62qSFWQSu61qDFv/ZFcWaBaqMIjHp70GZkr0keQAAvISxaoA8/heM="
