language: node_js
node_js:
  - "node"
script:
  -
deploy:
  provider: firebase
  token:
    secure: 6KB11dg+o32C9Q63I0NF70nB3kn1+UAqZEf0OpzPRm88wmnJAzYxpowzKf9U/UJcnvAyepDNF4kvaPhV+cQ87CiPN43Jd9S5s7bOUDnZWCpNowaon+BM+/f6BycUY+XrvJEk4ROYdD9c0j8i5dW6e5vb/MLglFUrOwwcCjpzCvPIwqi+6fWRDjUeNhFrw4jaf6fYTxvh8VqHjsOaR2i8CmtgE5fcl81gXJXXbFFozh3B8itl07R4NL0RKMINVUXhoXtIIU6uJ2WmFhrMOdP5C7JTrjR9vWRai5/jku4OdLcEcVXmu60dKO2Wn9sMvOiDO2lgvyBTnCkHVVn/hGEQUWev5R7ugzGzQuHtEC4hd3ebPgv3Y0Pe49w3tMfKJGQ96QsayCxNJiVdZBWaloX52r7wlKk7hD1rJ2GPtNOOwsEsE08BSirHSVE8QFtrqGHPRV/tH3DNgKQOUGuOwybyKmoOo7z23swtXrH3+A6t36fgDJD3D+cnrIVYlOoPxWpFFVuhrCQ/eVq/BbP9/PaWEVMcnzrWD2Qra6+hrxefc4kBacafm3Tq6hX9DuFB5UNUEipDDtIYXtPZSFnIDR1xbUJPuBJp4mxurWUPIBwTTYMiVU9mRXFpgTEU/CIzyMC6uPK3w8S9PvQF+WLfIDM8JHg5VNsfvAqwsvYi8CKNRuA=
