language: node_js
node_js:
- node
script:
- 
deploy:
  provider: firebase
  token:
    secure: ZBlAqIvKdGYxmN+kQfXC0Madx/ZKweNeeVt/rrIa1MA2MZycMZAOz2GQXjLWT0Wj7sbSenPz8S5B6AABqp4UENXSoTGyxG1BfXNZSEKk4oYSeoW9eZ8qeEjGwy7ez//dnWRhUtivECkTlPK+zzE+429ySQdFfsIPimXWQ3JxmlPY2sUKltC/ZGsHZFRo6kRzxENriIsiFOreuT5Sgujdm6rNoRuDkGwdXa4hwfHCKFiq1vhh+Mm6wQgOTGFDO16ZtG+QPCfaAEyS3Y6xJ6mzV5kHPP8WyWK+w+zb+GW90kqvEH+bWUF0hWVpkNuZK+ARnlTeZ8FZVqxrrdZJfGr8Zcv4mUYGzU0A0lUwHtOa2H6fkYgKgY4PZe0FlOhR6F1gBfsiFKrzqomIRhVlW7AhMKQl7s4PLzAgkP5xGswkPOrdKGk1xRT51vi62etoZlM2npHkwF/cYTt9e+b2aK9kfBSEG7uqtm4WJSfUWIoZUeJjSDyBIH7pVmnk5/hc6YI4zs7MguGDqiMZDEXY/2k+T4AkBRF8+9pv8qKRR57aNYH59yXckY9eCpqgnd70naQF6evfNdtKh6ovBMjCqxR4/oft4dYbDEVuclqbhCjq2+k+5MLNkQRe0h48Ar+IIbEaFraZVUed6J/d4TKlcat3y2NKkU8u0ZfPLNCncUvvgGE=
